---
gems:
  coffee-script-source:
    url: https://github.com/jashkenas/coffeescript/
  erubis:
    url: https://github.com/kwatch/erubis
  ffi-compiler:
    url: https://github.com/ffi/ffi
  foundation-rails:
    url: https://github.com/foundation/foundation-rails
  guard-compat:
    url: https://github.com/guard/guard-compat
  spoon:
    url: https://github.com/headius/spoon
  shellany:
    url: https://github.com/guard/shellany
  vegas:
    url: https://github.com/quirkey/vegas
  zipruby:
    url: https://github.com/fjg/zipruby
  gli:
    url: https://github.com/davetron5000/gli
  zen_to_i:
    url: https://github.com/yoshitsugu/zen_to_i
  trailblazer-option:
    url: https://github.com/trailblazer/trailblazer-option
  fog-sakuracloud:
    url: https://github.com/fog/fog-sakuracloud
  ovirt-engine-sdk:
    url: https://github.com/oVirt/ovirt-engine-sdk-ruby
  declarative_policy:
    url: https://gitlab.com/gitlab-org/ruby/gems/declarative-policy
  spamcheck:
    url: https://gitlab.com/gitlab-com/gl-security/engineering-and-research/automation-team/spam/spamcheck
  tanuki_emoji:
    url: https://gitlab.com/gitlab-org/ruby/gems/tanuki_emoji
  cbor:
    url: https://github.com/cabo/cbor-ruby
  expression_parser:
    url: https://github.com/nricciar/expression_parser
  extended-markdown-filter:
    url: https://github.com/gjtorikian/extended-markdown-filter
  gettext:
    url: https://github.com/ruby-gettext/gettext
  png_quantizator:
    url: https://github.com/rogercampos/png_quantizator
  redis-actionpack:
    url: https://github.com/redis-store/redis-actionpack
  redis-rack:
    url: https://github.com/redis-store/redis-rack
  sixarm_ruby_unaccent:
    url: https://github.com/SixArm/sixarm_ruby_unaccent
  thrift:
    url: https://github.com/szechyjs/thrift-gem
  vmstat:
    url: https://github.com/threez/ruby-vmstat
  mongoid-rspec:
    url: https://github.com/mongoid/mongoid-rspec
  rack-test:
    url: https://github.com/rack/rack-test
  jmespath:
    url: https://github.com/jmespath/jmespath.rb
  slack-notifier:
    url: https://github.com/slack-notifier/slack-notifier
  ipaddress:
    url: https://github.com/ipaddress-gem/ipaddress
  fog-powerdns:
    url: https://github.com/fog/fog-powerdns
  html_tokenizer:
    url: https://github.com/EiNSTeiN-/html_tokenizer
